sudo: required

language: python

services:
  - docker

addons:
  ssh_known_hosts:
    - diogoosorio.com

script:
  - docker build -t diogoosorio/blog .
  - docker run --rm diogoosorio/blog pylint src

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      docker push diogoosorio/blog
    fi

before_deploy:
  - eval "$(ssh-agent -s)"
  - echo "$SSH_DEPLOY_KEY" > /tmp/deploy_rsa
  - chmod 0600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: deploy.sh
  on:
    branch: master
