sudo: required

services:
  - docker

addons:
  ssh_known_hosts:
    - diogoosorio.com

before_install:
  - openssl aes-256-cbc -K $encrypted_d0a48cd1d4a3_key -iv $encrypted_d0a48cd1d4a3_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d

script:
  - docker build -t diogoosorio/blog .
  - docker run --rm diogoosorio/blog pylint src

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      docker push diogoosorio/blog
    fi

before_deploy:
  - chmod 0600 /tmp/deploy_rsa
  - eval "$(ssh-agent -s)"
  - ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: deploy.sh
  on:
    branch: master
