version: '3'

services:
  blog:
    build: .
    container_name: blog
    depends_on:
      - memcached
    environment:
      - FLASK_SECRET
      - ENVIRONMENT

  memcached:
    image: memcached:1.5
    container_name: memcached

  nginx:
    image: nginx:1.13
    container_name: nginx
    depends_on:
      - blog
    volumes:
      - ./etc/nginx/diogoosorio.conf:/etc/nginx/conf.d/diogoosorio.conf
      - nginx-logs:/www/diogoosorio.com/logs/nginx
      - nginx-certs:/etc/nginx/certs
    ports:
      - 80:80
      - 443:443

volumes:
  nginx-logs:
  nginx-certs:
