version: '3'

services:
  blog:
    build: .
    container_name: blog
    depends_on:
      - memcached
    environment:
      - FLASK_SECRET
      - ENVIRONMENT
    ports:
      - 4000:4000
    volumes:
      - .:/app

  memcached:
    image: memcached:1.5
    container_name: memcached
